apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

      - job_name: istiod
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - istio-system

        metrics_path: /metrics
        scheme: http

        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: istiod

          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: $1:15014

      - job_name: ztunnel
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - istio-system

        metrics_path: /metrics
        scheme: http

        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_name]
            action: keep
            regex: ztunnel-.+

          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: $1:15020
