apiVersion: apps/v1
kind: Deployment

metadata:
  name: security-demo-api
  labels:
    app: security-demo-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: security-demo-api

  template:
    metadata:
      labels:
        app: security-demo-api

    spec:
      serviceAccountName: security-demo-api

      containers:
        - name: security-demo-api
          image: ghcr.io/arhavinth/security-demo-api@sha256:938b96816338455340b1cb4b7d71126f184aa32b0eb0545d19ac85d79d9ca9d8
          ports:
            - containerPort: 8080

          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
