name: Security Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep SAST
        uses: semgrep/semgrep-action@v1
        with:
          config: p/python
        continue-on-error: true
      
      - name: Run Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

      - name: Run Trivy dependency scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: application
          severity: CRITICAL,HIGH,MEDIUM
          ignore-unfixed: true
          exit-code: '0'


      - name: Run Checkov IaC scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infrastructure/terraform
        continue-on-error: true

      - name: Run Trivy Kubernetes manifest scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: kubernetes
          severity: CRITICAL,HIGH,MEDIUM
          exit-code: '0'

      - name: Install Conftest
        run: |
          curl -L https://github.com/open-policy-agent/conftest/releases/download/v0.70.1/conftest_0.70.1_Linux_x86_64.tar.gz \
            -o conftest.tar.gz
          tar -xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/conftest
          conftest --version

      - name: Run OPA policy checks
        run: |
          conftest test kubernetes/base/deployment.yaml \
            --policy policy/kubernetes

      - name: Build Docker image
        run: |
          docker build \
            -t security-demo-api:${{ github.sha }} \
            ./application

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: security-demo-api:${{ github.sha }}
          format: cyclonedx-json
          output-file: sbom.json
          artifact-name: security-demo-api-sbom

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: security-demo-api:${{ github.sha }}
          format: table
          severity: CRITICAL,HIGH,MEDIUM
          ignore-unfixed: true
          exit-code: '0'